jail_settings:
  punish-chat: true
  chat-format: "ยง8{username}: ยง7{message}"
  language: "ru"
  material: "OBSIDIAN"
  allowed_commands:
    - "/jail"
    - ""
jail_area:
  world: "world"
  x: 0
  y: 0
  z: 0